name = "tg-double-chat-bot"
main = "worker.js"
compatibility_date = "2026-06-05"
keep_vars = true

[[kv_namespaces]]
binding = "USER_KV"
id = "75b9149ac0f54613a233513d940d9415"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
